/* Offline design demonstration. No SketchUp, network or persistent writes. */
(()=>{'use strict';const $=id=>document.getElementById(id),chat=$('chat'),empty=$('chatEmpty');let timer;const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function clone(id){return $(id).content.firstElementChild.cloneNode(true)}
function status(value,label){$('app').dataset.state=value;document.querySelector('.topbar__statusText').textContent=label;$('btnSend').disabled=value!=='connected';$('input').disabled=value!=='connected';$('btnCancel').hidden=value!=='busy'}
function message(role,text){empty.hidden=true;const el=clone('tplMessage');el.classList.add('msg--'+role);el.querySelector('.msg__role').textContent=role==='user'?'ВЫ':role==='assistant'?'Stultus':'';el.querySelector('.msg__body').innerHTML=text;chat.append(el);return el}
function tool(label,state='ok',code='group = model.active_entities.add_group\ngroup.name = "Пергола / 01"\n# Создание элементов в текущей модели'){const el=clone('tplTool');el.dataset.state=state;el.querySelector('.tool__label').textContent=label;el.querySelector('.tool__name').textContent='execute_ruby';el.querySelector('.tool__state').textContent=state==='ok'?'готово':state==='error'?'ошибка':'в работе';el.querySelector('.tool__args').textContent=code;el.querySelector('.tool__result').textContent=state==='error'?'ArgumentError: недопустимая длина ребра.\nОперация отменена. Модель не изменена.':'Операция выполнена · отдельная группа';chat.append(el);return el}
function base(){const label=document.createElement('div');label.className='session-label';label.innerHTML='ПЕРГОЛА НА ТЕРРАСЕ <time>01</time>';chat.append(label);message('user','Добавь перголу над террасой. Тонкие стойки, плоская кровля с ламелями. Габариты 6 × 4 м, высота 2,8 м.');message('assistant','Построю лёгкую конструкцию в границах террасы. Сначала проверю сцену и положение основания.');tool('Сцена и выделение прочитаны','ok','{\n  "selection": ["Терраса"],\n  "bounds_mm": [6000, 4000, 150],\n  "units": "millimeters"\n}');}
function preview(){const f=document.createElement('figure');f.className='viewport';f.innerHTML='<div class="viewport__head">◇ <span>Пергола / перспектива</span><span>ДЕМО-ВИД</span></div><img src="pergola.svg" alt="Демонстрационная аксонометрия перголы с ламелями на террасе"><figcaption><span>6 000 × 4 000 × 2 800 мм</span><span>01 / Геометрия</span></figcaption>';chat.append(f)}
function ask(){const el=clone('tplAsk');el.querySelector('.card__text').textContent='Какой материал используем для стоек и ламелей? Размеры конструкции останутся прежними.';['Тёмный металл','Светлое дерево','Без материала'].forEach((s,i)=>{let b=document.createElement('button');b.className='btn'+(i===0?' btn--primary':'');b.textContent=s;b.onclick=()=>{el.classList.add('is-done');el.querySelector('.card__text').textContent='Выбрано: '+s;message('user',esc(s));message('assistant','В рабочем плагине здесь продолжится построение с выбранным материалом.');chat.scrollTop=chat.scrollHeight};el.querySelector('.card__options').append(b)});chat.append(el)}
function shot(){const el=clone('tplShot');el.querySelector('.card__text').textContent='Конструкция готова. Снимок текущего вида поможет проверить пропорции и положение ламелей.';el.querySelector('[data-act=allow]').onclick=()=>{el.classList.add('is-done');const img=el.querySelector('img');img.src='pergola.svg';img.hidden=false;img.alt='Демонстрационный вид перголы';el.querySelector('.card__text').textContent='Демонстрационный снимок. В плагине здесь будет текущий вьюпорт.';chat.scrollTop=chat.scrollHeight};el.querySelector('[data-act=deny]').onclick=()=>{el.classList.add('is-done');el.querySelector('.card__text').textContent='Снимок не сделан. Продолжаем без него.'};chat.append(el)}
function settings(){$('settings').hidden=false;$('setGateway').value='wss://studio.example/ws';$('setToken').value='';$('settingsInfo').textContent='Демонстрация подключения · данные не отправляются'}
function show(state){clearTimeout(timer);chat.querySelectorAll(':scope > :not(#chatEmpty)').forEach(el=>el.remove());empty.hidden=state!=='empty';$('settings').hidden=true;$('composerHint').textContent='';$('input').value='';$('usage').textContent='';status('connected','На связи');if(state==='empty'){return}if(state==='disconnected'){empty.hidden=false;status('disconnected','Нет связи');$('composerHint').textContent='Сервер недоступен. Проверьте подключение в настройках.';return}if(state==='connecting'){empty.hidden=false;status('connecting','Подключение');$('composerHint').textContent='Устанавливаем соединение с сервером…';return}base();if(state==='ask'){ask();$('composerHint').textContent='Выберите вариант или напишите свой ответ.'}else if(state==='error'){tool('Не удалось создать ламели','error').open=true;message('error','Построение остановлено. Проверьте размер выделенной грани и повторите запрос.')}else if(state==='busy'){tool('Создаю стойки и верхнюю обвязку','running');status('busy','Строю');$('composerHint').textContent='Работаю с геометрией. Можно остановить выполнение.'}else{tool('Построены стойки и верхняя обвязка');tool('Добавлены 24 ламели');if(state==='shot'){shot();status('busy','Жду решения');$('composerHint').textContent='Нужно разрешение на снимок вьюпорта.'}else{message('assistant','<strong>Готово. Пергола на месте.</strong><p>Четыре стойки, тонкая обвязка и 24 ламели. Конструкция собрана в отдельную группу.</p>');preview();const note=document.createElement('div');note.className='result-note';note.textContent='Один шаг отмены в SketchUp · Ctrl + Z';chat.append(note);$('usage').textContent='2,4k вх / 860 вых · $0,018'}}if(state==='settings')settings();chat.scrollTop=0; if(state!=='settings'){requestAnimationFrame(()=>{chat.scrollTop=chat.scrollHeight});chat.querySelectorAll('img').forEach(img=>img.addEventListener('load',()=>{chat.scrollTop=chat.scrollHeight},{once:true}));}}
$('modelTitle').textContent='Терраса_концепт.skp';$('providerSelect').innerHTML='<option>Claude</option><option>Codex</option>';
function models(){$('modelSelect').innerHTML=$('providerSelect').value==='Claude'?'<option>Sonnet</option><option>Opus</option>':'<option>Основная модель</option><option disabled>Другая · не настроена</option>'}models();$('providerSelect').onchange=models;
$('btnSettings').onclick=settings;$('btnCloseSettings').onclick=()=>{$('settings').hidden=true};$('btnSaveSettings').onclick=()=>{if(!$('setGateway').value.trim()){$('settingsInfo').textContent='Введите адрес сервера.';return}$('settings').hidden=true;status('connecting','Подключение');$('composerHint').textContent='Демонстрация подключения…';timer=setTimeout(()=>{status('connected','На связи');$('composerHint').textContent='Демонстрация: соединение имитировано, данные не отправлялись.'},900)};
$('btnNew').onclick=()=>show('empty');$('btnClearHistory').onclick=()=>show('empty');$('btnCancel').onclick=()=>{clearTimeout(timer);status('connected','На связи');chat.querySelectorAll('.tool[data-state=running]').forEach(el=>{el.dataset.state='error';el.querySelector('.tool__state').textContent='остановлено'});$('composerHint').textContent='Выполнение остановлено.'};
function send(){const value=$('input').value.trim();if(!value||$('app').dataset.state!=='connected')return;message('user',esc(value));$('input').value='';status('busy','Думаю');$('composerHint').textContent='Демонстрация ответа…';timer=setTimeout(()=>{message('assistant','Это интерактивный макет. В рабочем плагине ваш запрос будет передан выбранной модели и выполнен в SketchUp.');status('connected','На связи');$('composerHint').textContent='';chat.scrollTop=chat.scrollHeight},900);chat.scrollTop=chat.scrollHeight}
$('btnSend').onclick=send;$('input').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();send()}});window.demo={show};show(new URLSearchParams(location.search).get('state')||'conversation');})();
